### ISSUE TITLE
NeoForge 1.21.1+ Port?

### ISSUE THREAD

**Issue by penturt** [infernalstudios/Nekos-Enchanted-Books#59]
any plans to port to NeoForge 1.21.1+?

**Comment by SwanX1** [comment]
![infernal_expansion_server](https://github.com/user-attachments/assets/bdcfa84f-72b4-487d-ae14-0f297d07e1c2)

**Comment by SwanX1** [comment]
Yes, but no promises, since our devs are busy with life right now. As you might expect from a passion project started over 4 years ago, a lot has changed in our personal lives, and we can't dedicate the same amount of attention as when we first started.
I, for example, was in high school when I joined the team, and now I'm attending university - the change is drastic and warrants my full attention, and any free time I have is spent on other stuff.
Sorry about the long rant, I hope you understand.

Sincerely,
Me :)

**Comment by penturt** [comment]
I'm completely understand, thank you for the reply.
